name: CashFlow
main: mveritym.cashflow.CashFlow
version: 0.1
commands:
   createtax:
      description: Creates a tax.
      permission: cashflow.basic
      usage: |
           /createtax [tax name] [% of income] [interval] [receiving player]
   deletetax:
      description: Deletes a tax.
      permission: cashflow.basic
      usage: |
           /deletetax [tax name]
   listtaxes:
      description: Lists each tax.
      permission: cashflow.basic
      usage: |
           /listtaxes
permissions:
    cashflow.*:
        description: Allows access to all cashflow commands.
        children:
            cashflow.createtax: true
            cashflow.deletetax: true
            cashflow.listtax: true
        default: false
    cashflow.createtax:
        description: Allows you to create a tax.
        default: false
    cashflow.deletetax:
        description: Allows you to delete a tax.
        default: false
    cashflow.listtaxes:
        description: Allows you to see a list of all taxes.
        default: false