name: CashFlow
main: mveritym.cashflow.CashFlow
version: 0.4
commands:
    tax:
      description: Provides access to tax commands.
      usage: |
           Usage:
           /<command> create <taxname> <percentincome> <interval> [payee] - Creates a tax
           /<command> delete <taxname> - Deletes a tax
           /<command> apply group <taxname> <groupnames> - Applies groups to a tax (comma separated)
           /<command> remove group <taxname> <groupnames> - Removes a group from a tax (comma separated)
           <command> apply player <taxname> <playernames> - Applies players to a tax (comma separated)
           /<command> remove player <taxname> <playernames> - Removes a player from a tax (comma separated)
           /<command> addexception <taxname> <playername> - Adds the player as an exception (case sensitive!)
           /<command> removeexception <taxname> <playername> - Removes the player as an exception (case sensitive!)
           /<command> list - Lists each tax
           /<command> info <taxname> - Lists information about a tax
    salary:
      description: Provides access to salary commands.
      usage: |
          Usage:
          /<command> create <salaryname> <salary> <interval> [employer] - Creates a salary
          /<command> delete <salaryname> - Deletes a salary
          /<command> apply group <salaryname> <groupnames> - Applies groups to a salary (comma separated)
          /<command> apply player <salaryname> <playernames> - Applies players to a salary (comma separated)
          /<command> remove group <salaryname> <groupnames> - Removes groups from a salary (comma separated)
          /<command> remove player <salaryname> <playernames> - Removes players from a salary (comma separated)
          /<command> addexception <taxname> <playername> - Adds the player as an exception
          /<command> removeexception <taxname> <playername> - Removes the player as an exception
          /<command> list - Lists each salary
          /<command> info <salaryname> - Lists information about a salary
    cashflow:
        description: Lets you enable, disable, restart or set the world.
        usage: |
            Usage:
            /<command> enable - Enables payment of taxes and salaries.
            /<command> disable - Disables payment of taxes and salaries.
            /<command> restart - Disables then enables payment of taxes and salaries. Use this to refresh timer threads.
            /<command> setworld - Specifies the world name so you can create taxes/salaries that go to/come from offline players.
            /<command> setonlineonly <true/false> - Lets you specify if taxes apply to only online players or all players.
permissions:
    cashflow.*:
        description: Allows access to all cashflow commands.
        children:
            cashflow.tax: true
            cashflow.salary: true
            cashflow.basic: true
        default: false
    cashflow.tax: 
        description: Allows control of tax commands.
        default: false
    cashflow.salary:
        description: Allows control of salary commands.
        default: false
    cashflow.basic:
        description: Allows access to the enable, disable, restart and setworld commands.