name: CashFlow
main: mveritym.cashflow.CashFlow
version: 0.1
commands:
    tax:
      description: Provides access to tax commands.
      permission: cashflow.tax
      usage: |
           Usage:
           /<command> create <taxname> <percentincome> <interval> [payee] - Creates a tax
           /<command> delete <taxname> - Deletes a tax
           /<command> apply <taxname> <groupname> - Applies a group to a tax
           /<command> remove <taxname> <groupname> - Removes a group from a tax
           /<command> list - Lists each tax
           /<command> info <taxname> - Lists information about a tax
    salary:
      description: Provides access to salary commands.
      permission: cashflow.salary
      usage: |
          Usage:
          /<command> create <salaryname> <salary> <interval> [employer] - Creates a salary
    enable:
      description: Starts timers for each tax and salary.
      permission: cashflow.enable
      usage: |
           /<command>
    disable:
      description: Removes timers for each tax and salary.
      permission: cashflow.disable
      usage: |
           /<command>
    restart:
      description: Disables and re-enables taxes. Used after creating or deleting taxes while taxes are enabled.
      permission: cashflow.reload
      usage: |
           /<command>
permissions:
    cashflow.*:
        description: Allows access to all cashflow commands.
        children:
            cashflow.tax: true
            cashflow.salary: true
            cashflow.enable: true
            cashflow.disable: true
            cashflow.restart: true
        default: false
    cashflow.tax: 
        description: Allows control of tax commands.
        default: false
    cashflow.salary:
        description: Allows control of salary commands.
        default: false
    cashflow.enable:
        description: Allows user to enable taxes and salaries.
        default: false
    cashflow.disable:
        description: Allows user to disable taxes and salaries.
    cashflow.restart:
        description: Allows user to reload taxes and salaries.
        default: false 