name: CashFlow
main: mveritym.cashflow.CashFlow
version: 0.1
commands:
   test:
      description: This is a demo command.
      permission: cashflow.basic
      usage: |
           /test
   createtax:
      description: Creates a tax.
      permission: cashflow.basic
      usage: |
           /createtax [name of tax] [% of income] [interval] [receiving player]