name: CashFlow
main: mveritym.cashflow.CashFlow
version: 0.1
commands:
   createtax:
      description: Creates a tax.
      permission: cashflow.basic
      usage: |
           /createtax [tax name] [% of income] [interval] [receiving player]
   deletetax:
      description: Deletes a tax.
      permission: cashflow.basic
      usage: |
           /deletetax [tax name]
   listtaxes:
      description: Lists each tax.
      permission: cashflow.basic
      usage: |
           /listalltaxes